### ISSUE TITLE
More precise value type in setCustomVariable

### ISSUE THREAD

**Issue by yguedidi** [tideways/ext-tideways-stubs#2]
Currently it is `mixed` which is quite vague.
In my early days with tideways I tried to set an array value, and it didn't work. :sweat_smile: 
It seems that it supports only `string|int|float|bool|null`, so maybe it could be a good idea to show that in the PHPDoc?

I can quickly work on a PR, but I can't confirm that the above type list is the right one

**Comment by beberlei** [comment]
Since the latest version if the value is not a string, its tried to be casted to be a string. So everything "will" work however it can throw errors (object without __toString) or warning (array). `Stringable` is new, so maybe `object|string|int|float|bool|null` ?

**Comment by yguedidi** [comment]
@beberlei I just opened a quick PR with your suggested typehint :)
